### ISSUE TITLE
Why is term.js-cli needed?

### ISSUE THREAD

**Issue by kevinsimper** [scaleway/scaleway-cli#160]
I thought it was just a command for ssh, but it was not.

Why wouldn't it just execute normal `ssh`?

**Comment by kevinsimper** [comment]
I have manually put in my ssh public key on scaleway.com.

I installed `npm install -g term.js-cli` and then tried again and I had to provide a username and password, even through I have none, and ssh already works perfect.

My ssh-agent is running and have my public key added.

I can not understand the flow here? How exactly are you suppose to work with this?

**Comment by ebfe** [comment]
As far as I can tell `swc attach` connects to the serial port of your instance. So that works even when ssh is not running and is very useful when debugging the boot process.

**Comment by moul** [comment]
@kevinsimper, as @ebfe said,
the **term.js-cli** binary is only used for the `scw attach` and `scw run --attach` commands.

For `scw exec` and `scw run` we are using standard **ssh**.

---

And about the user of `term.js-cli` in particular, that's because we are using [term.js](https://github.com/chjj/term.js) to export the **serial console** to HTTP, and term.js uses [socket.io](http://socket.io), which isn't actually practical to use in Golang.

We are planning to replace **term.js** with an alternative using **websocket** instead of **socket.io**, as soon as the switch is made, we will remove the **term.js-cli** dependency and use Golang's websocket + TTY builtins.
