### ISSUE TITLE
Argument type for "tags" is inconsistent and misleading for "scw instance server list"

### ISSUE THREAD

**Issue by FredTreg** [scaleway/scaleway-cli#3231]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

Let's say you need to search for all instances having two tags: `current` and `monitoring`. One would expect to be able to run the command:

```
scw instance server list tags=current,monitoring
```
instead I have to run the command (notice the `.0`):
```
scw instance server list tags.0=current,monitoring
```

### Expected Behavior

I would except this command to work using just `tags=XXX,YYY` instead of failing as:
1) This is aligned with the REST API (one `tags` field with comma separated values)
2) This is homogeneous with other commands which work and do not require the index, such as `scw instance image list tags=current,monitoring`
3) The command also accepts `tags.1` and so on as arguments but they are ignored which is misleading.

### Actual Behavior

Command fails:
```
root ➜ /workspace $ scw instance server list tags=current,monitoring
Cannot unmarshal arg 'tags=current,monitoring': missing index on the array
```

## More info

```
Version    2.16.1
BuildDate  2023-06-13T12:10:41Z
GoVersion  go1.20.4
GitBranch  HEAD
GitCommit  0bce8711
GoArch     amd64
GoOS       linux
```

**Comment by Codelax** [comment]
Hi, listing server works with `scw instance server list tags.0=current tags.1=monitoring`.
Using index is the expected behavior for arrays/lists and it can be seen in most commands (`rdb instance list`, `instance ip list`, `instance volume list`, ...).

The issue is that the image listing command use a tag list with comas instead of arguments with indexes.
The coma separated list is more aligned with instance api but it does not follow the common api format at scaleway and instance is an exception here.

**Comment by FredTreg** [comment]
Yes you are correct, I think that my mistake came from having created a single tag "current,monitoring" (tag name includes a comma) as the Scaleway api allows it... and from there I was completely lost in my conclusions...

Anyway since the underlying api uses comma to separate tags, on can still use the `tags.0=current,monitoring` but I'll use the  `tags.0=current tags.1=monitoring` from now on.

BTW, I guess you meant "image is an exception here" instead of "instance is an exception here". If this is the case, then snapshot is an exception too...

Closing bug, thanks.

**Comment by FredTreg** [comment]
One last comment, I remember another misleading information when executing `scw instance server list --help`
We get:
```
  [tags.{index}]      List Instances with these exact tags (to filter with several tags, use commas to separate them)
```
So is it indexes or commas?

**Comment by NicolasCARPi** [comment]
Hello,

On the `scw instance volume list -h` output, we see:

`[tags]              Filter volumes with these exact tags (to filter with several tags, use commas to separate them)`

But it should be like the comment above, with `tags.{index}`, right?

Also, it would be great if instead of: `Cannot unmarshal arg 'tags=data': missing index on the array`, a more user friendly message could be printed, such as one hinting that using `tags.0=data` is probably what the user wants. At first I thought it was a bug because the usage and the help doc differ. @FredTreg maybe this should be re-opened as a doc issue rather than a bug?
