### ISSUE TITLE
UDP CONNECTIONS DON'T WORK!!!

### ISSUE THREAD

**Issue by ALEX778899** [scaleway/scaleway-cli#485]
Hello,
scaleway.com support team told us to open an issue here.
IOTA IRI can't work in scaleway.com with UDP protocol, we tested IOTA IRI with other VPS companies and works like a charm.
The problem could be you check the size of packets and for security doesn’t accept to fragment.
You can easy test it the UDP problem from YOUR SIDE, just use https://hub.docker.com/r/bluedigits/iota-node/
I advice you to solve the problem ASAP because IOTA is growing, works very fast with UDP protocol and scaleway.com is loosing a lot of IOTA customers.....

Please let me know ASAP
Thanks in advance

**Comment by akomelj** [comment]
I concur - UDP fragmentation is the problem and IOTA uses larger UDP packets. I haven't tried VPS servers but I can confirm that it does not work on baremetal servers.

Instead of running IOTA in a Docker container, you can use `nping` to send large UDP packets to Scaleway VPS/baremetal server and monitor received packets with tcpdump. You will see that UDP fragments get discarded.

I.e. `nping --udp -p <VPS port> --data-length 1650 <VPS IP>` will send UDP packet of 1650 bytes to selected IP and port.

This issue is really annoying as more and more IOTA nodes are using UDP due to Nelson and TCP bugs in IRI.

**Comment by brmzkw** [comment]
Hi,

We've been in the rush in the last few days, but I'll give an answer to the issue as soon as possible.

**Comment by brmzkw** [comment]
Hi,

We improve the NAT located in Paris. Can you please retry?

**Comment by akomelj** [comment]
No, it's still the same. Only 1480 bytes (in a UDP frame of 1514 bytes) arrive when sent from outside network.

Tested with `nping --udp -p <VPS port> --data-length 1650 <VPS IP>` on the sending side and `tcpdump -i eth0 -s 2048 -w udp.pcap udp port <VPS port>` on the receiving side (parameter `-s 2048`: store 2k of packet data to output packet file `-w`). PCAP file contains shortened packets.

**Comment by viossat** [comment]
Still the same here.

**Comment by carbonimax** [comment]
Same issue for me today

**Comment by zoran** [comment]
same here

**Comment by mmarchand** [comment]
Hi guys, I can confirm we identified the issue (though a bit tricky), it's not a simple and quick fix, but the team is working on it
I hope to have good news within the next few weeks, thanks for your patience

**Comment by DarkShimy00** [comment]
Do you have any updates?

**Comment by mmarchand** [comment]
yes, we have a fix, I am checking for deployment ETA now

**Comment by DarkShimy00** [comment]
Hi, any news on that?

**Comment by mmarchand** [comment]
should be in production on all NAT servers within the next week

**Comment by justinclift** [comment]
@akomelj Have you had a chance to retest this from your end? :smile:

**Comment by akomelj** [comment]
Hi, sorry for the delay - I actually didn't know that the fix was had already been installed. :-(

Anyway, I have just run the tests and now it appears that all fragments are coming through. Great!

Wireshark dump screenshots w/ all fragments:
![selection_022](https://user-images.githubusercontent.com/23163209/48058751-84518580-e1b7-11e8-8566-742ce12183dc.jpg)

**Comment by ALEX778899** [comment]
Too much time, I don't need anymore.

**Comment by justinclift** [comment]
Excellent.  Thanks for testing and confirming @akomelj. :smile:
