### ISSUE TITLE
Panic when trying to attach to a starting server

### ISSUE THREAD

**Issue by sieben** [scaleway/scaleway-cli#497]
I've stumbled upon the following error when trying to test the attach command:

## Step to reproduce

```
$ ./scw create OpenVPN
94c7fc5f-e689-460a-bb8c-8f87e28ed654
```
```
$ ./scw start 94c7fc5f-e689-460a-bb8c-8f87e28ed654
94c7fc5f-e689-460a-bb8c-8f87e28ed654
```

```
$ ./scw attach 94c7fc5f
You are connected, type 'Ctrl+q' to quit.
......panic: runtime error: index out of range

goroutine 54 [running]:
github.com/scaleway/scaleway-cli/vendor/github.com/moby/moby/pkg/term.(*escapeProxy).Read(0xc4204467b0, 0xc42042a300, 0x80, 0x80, 0xc42000e010, 0x0, 0x0)
	/Users/sieben/go/src/github.com/scaleway/scaleway-cli/vendor/github.com/moby/moby/pkg/term/proxy.go:54 +0x5f5
github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client.(*Client).writeLoop(0xc420084660, 0xc4202cc270, 0x0)
	/Users/sieben/go/src/github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client/gotty-client.go:352 +0x392
created by github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client.(*Client).Loop
	/Users/sieben/go/src/github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client/gotty-client.go:238 +0x110
```

**Comment by Sh4d1** [comment]
Hey, I stumbled into the same issue.

It occurs here because `r.escapeKeys` is empty and `r.escapeKeyPos` is `0`.
https://github.com/scaleway/scaleway-cli/blob/53548bf67d9a32a2dcc8d627d1bd83ae4a3bf414/vendor/github.com/moby/moby/pkg/term/proxy.go#L54

I added this line before:
```
if len(r.escapeKeys) == 0 {                                 
    return nr, nil
}
```

and it is working now.
Though I'm not sure if it is the right solution (we could add some EscapeKeys to this array if needed).

I openend an issue and a PR in moby/moby:
https://github.com/moby/moby/issues/36917
https://github.com/moby/moby/pull/36918

**Comment by Sh4d1** [comment]
@moul will you bump the dependencies or should I PR it?

**Comment by rprimus** [comment]
Wed May  2 19:08:40 BST 2018

Hi,

Any idea when this will be fixed?

**Comment by Sh4d1** [comment]
Once the PR just referenced above your comment will be merged and the dependencies of scaleway-cli are bumped :)

**Comment by felixsanz** [comment]
can the deps be bumped?

**Comment by Sh4d1** [comment]
@felixsanz waiting for #506 to be merged in fact :roll_eyes:

**Comment by Sh4d1** [comment]
@felixsanz merged ;)
