### ISSUE TITLE
Sentry Error?

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#499]
```
$ ./scw -D attach ffcd289e
DEBU[0000] Connection to https://tty-par1.scaleway.com/v2/?arg=3f47849c-a76f-48d0-ad7a-a85f4904a724&arg=ffcd289e-1ccc-40ac-b580-ab39ec794130
DEBU[0000] Fetching auth token auth-token: "https://tty-par1.scaleway.com/v2/auth_token.js?arg=3f47849c-a76f-48d0-ad7a-a85f4904a724&arg=ffcd289e-1ccc-40ac-b580-ab39ec794130"
DEBU[0000] Auth-token: ""
DEBU[0000] Connecting to websocket: "wss://tty-par1.scaleway.com/v2/ws?arg=3f47849c-a76f-48d0-ad7a-a85f4904a724&arg=ffcd289e-1ccc-40ac-b580-ab39ec794130"
DEBU[0000] Sending arguments and auth-token
You are connected, type 'Ctrl+q' to quit.
DEBU[0000] Sending ping
DEBU[0000] Unhandled protocol message: json pref: {"background-color":"rgb(16, 16, 16)","background-image":"url(https://cdn.rawgit.com/scaleway/tty.scaleway.com/a033909d13d181d600dd6b544b30e76ae75129a9/assets/scaleway-term-logo.svg)","background-position":"center center","cursor-blink":true,"font-size":12}
An error has occured
Failed to fire hook: no response from sentry server in 100ms
DEBU[0000] readLoop suicide
DEBU[0000] termsizeLoop died
DEBU[0000] writeLoop died
DEBU[0000] Client.Loop() exiting
DEBU[0000] Writing cache file to disk
```

**Comment by Sh4d1** [comment]
I got this error as well, I thought it was linked to Scaleway not receiving the booted signal from the server, thus rebooting the instance?

**Comment by sieben** [comment]
@bchatelard @brmzkw ?

**Comment by brmzkw** [comment]
From my understanding, the problem has been introduced by https://github.com/scaleway/scaleway-cli/commit/6cd6b6ae20e31dbf6d73e5cd33cb12c28af7b64c and comes from https://github.com/scaleway/scaleway-cli/blob/master/vendor/github.com/moby/moby/pkg/term/proxy.go#L54

Dereferencing `r.escapeKeys` raises an error, since `escapeKeys` is empty.

To fix the issue, you can initialize EscapeKeys at https://github.com/scaleway/scaleway-cli/blob/master/vendor/github.com/moul/gotty-client/gotty-client.go#L472 with any value

```
	return &Client{
		Dialer:     &websocket.Dialer{},
		URL:        url,
		WriteMutex: &sync.Mutex{},
		Output:     os.Stdout,
		poison:     make(chan bool),
		EscapeKeys: []byte{'a'}, # Add this
	}, nil
```

It's obviously not the fix to make (setting "any value"), but I'm not sure about the effects of "EscapeKeys".

Any idea @moul ?

**Comment by moul** [comment]
Yes, it may come from the recent change in proxy.go,

another hypothesis: [gotty](https://github.com/yudai/gotty), the tool behind `tty-*.scaleway.com` recently moved to v2.0 with a new API

scaleway-cli uses [gotty-client](https://github.com/moul/gotty-client) which was also updated to be compatible with the V2, maybe retro-compatibility was not done correctly :/, sorry if this is the case

anyway, I don't have so much time in the following days to investigate more, but a solution to the two hypothesis is to fix a specific version/branch/commit of these dependencies to an older version and give a new try
