### ISSUE TITLE
Can't inspect snapshot

### ISSUE THREAD

**Issue by simonnilsson** [scaleway/scaleway-cli#510]
While trying to inspect a snapshot I get the following error:

```
scw images -f type=snapshot -q
6080db7b-0e1f-40fd-865d-1615d0545dc3

scw inspect 6080db7b-0e1f-40fd-865d-1615d0545dc3
ERRO[0000] Unable to resolve identifier 6080db7b-0e1f-40fd-865d-1615d0545dc3
FATA[0000] cannot execute 'inspect': at least 1 item failed to be inspected
```

Is this a bug or am I doing something wrong? From `scw inspect --help` inspecting snapshots should be possible.

**Comment by brmzkw** [comment]
Hello,

After spending some time to understand the problem by trying to follow the various goroutines/channels/callbacks/cache... It appears the problem comes from https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/api.go#L1693

`s.Cache.InsertSnapshot` takes two empty strings for the region and the architecture. If the first parameter is set to "par1" (assuming you are trying to inspect a snapshot from the paris region), a result is displayed.

I still need to find a way to dynamically get this value.
