### ISSUE TITLE
SCW API ssh fingerprints 404 / user_data is empty

### ISSUE THREAD

**Issue by Duneyr** [scaleway/scaleway-cli#512]
(SCW Support - fast, kind but meh - told me to go for github.scaleway.com (which does not exist) so I hope I am right here...)

Although working fine in the past, i cannot get the ssh fingerprints of my new instances from the scaleway api. It just returns 404 when going directly for the fingerprints and "{"user_data": []}" (working fine but empty) when going for the whole user data of the instance.

It worked for the old instances though.

Or in other words:

This should work, but it does not:
https://developer.scaleway.com/#user-data

(
User-data call
https://cp-par1.scaleway.com/servers/__THE_ID__/user_data
returns an empty result set {"user_data": []}

fingerprint
https://cp-par1.scaleway.com/servers/__THE_ID__/user_data/ssh-host-fingerprint
returns 404
)

**Comment by brmzkw** [comment]
Hello,

Thanks a lot for the report.

I think the issue comes from our new image format which makes possible to boot locally. We used to put ssh keys on the metadata API [here](https://github.com/scaleway/image-tools/blob/master/bases/overlay-common/usr/local/sbin/scw-generate-ssh-keys). I guess the script should be moved to a cloud-init script (which IMO will require to setup vendor-data).

@karibou @superseed can you please give a look to this issue? That's a regression we should resolve! :-)

**Comment by superseed** [comment]
Hi,

This is a mistake on my part, I decided to bypass the scw-generate-ssh-keys and go directly for a per-distrib method -- for example, Archlinux already implements a service that generates ssh host keys on first boot.

I'm fixing that asap !
