### ISSUE TITLE
Add a trash option (-t) to scw rm

### ISSUE THREAD

**Issue by jfyuen** [scaleway/scaleway-cli#526]
When a server is currently running, it is possible to stop it and trash the associated volume with `scw stop -t`.

It would be nice to have this option for `scw rm` to also trash the volume on a stopped server with `scw rm -t` for example.

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

For this particular, I invite you to take a look at `scw instance server terminate`
