### ISSUE TITLE
creating Debian_Stretch instances fails with "cannot execute 'create': Too many candidates for Debian_Stretch(2)"

### ISSUE THREAD

**Issue by asac** [scaleway/scaleway-cli#532]
I used to do this i believe and recently this started to fail:

```
scw --region=par1 create --commercial-type=C2S Debian_Stretch
  IMAGEID           FROM                            NAME                      ZONE                ARCH
- da6ebdf0          image:debian-stretch            Debian Stretch            par1                x86_64
- b7382648          image:debian-mini-stretch-25g   Debian Mini Stretch 25G   par1                x86_64
FATA[0000] cannot execute 'create': Too many candidates for Debian_Stretch (2) 
```

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

In your particular case, I would invite you to take a look at `scw marketplace image list`
