### ISSUE TITLE
scw create does not support full images UUID 

### ISSUE THREAD

**Issue by djalal** [scaleway/scaleway-cli#534]
When creating new servers, CLI expect an `IMAGE` parameter.

It works using short UUIDs or names, e.g `574a0d52 `

However it will fail with the full length UUID, e.g `574a0d52-bef4-42cf-b4b4-5a9c3163e68a`

**Error Message**

```
FATA[0001] cannot execute 'create': StatusCode: 404, Type: unknown_resource, APIMessage: "574a0d52-bef4-42cf-b4b4-5a9c3163e68a" not found
```

**How to reproduce**

```
scw create --volume="" --name="foobar" --commercial-type="START1-M" $(scw images -f "name=xenial type=image" -q | tail -n1)
```

**Comment by abitrolly** [comment]
The same problem here:
```
$ scw create e640c621-305b-45f5-975f-a3f80c1cec66
FATA[0000] cannot execute 'create': StatusCode: 404, Type: unknown_resource, APIMessage: "e640c621-305b-45f5-975f-a3f80c1cec66" not found 
```

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

In this particular case, I would invite you to take a look at `scw instance server create`
