### ISSUE TITLE
scw images and api don't provide same information

### ISSUE THREAD

**Issue by valvin1** [scaleway/scaleway-cli#582]
Hello,

I'm trying to use ansible module. To create a machine i need an image id.
I believed it will be easier using scw cli to get this id so I used this command : 

```
scw --region=ams1 images -f "name=buster" --no-trunc -q 
```
which returns : 

```
4c08096f-f825-429a-b91e-b974072ac813
```

If I do the same using API : 

```
curl -H "X-Auth-Token: ***" "https://api.scaleway.com/instance/v1/zones/nl-ams-1/images/?name=buster" |jq ".images[].id"
```
I get : 
```
"bce24b0c-cedc-484d-a4b1-616cf883dc0b"
"948d5610-86c2-414d-9d88-acc6be4b4842"
```
Difference between cli and api looks to be linked to the arch. API distinguish two different ID which is not the case for the cli.

If I use cli image ID Ansible module doesn't work. But if I use API image ID it works.

First I believe it was because ansible api endpoint was not up to date and fix it using the fix on Ansible commited 9 days ago but i get the same result. 

Is it a normal behaviour and I can't use the provided ID for Ansible ?

**Comment by QuentinBrosse** [comment]
Hi,

# Explanations

## Command

`scw images` command use the [marketplace API](https://api-marketplace.scaleway.com/images/) to find images. The returned image ID is the ID of the current version object of the image (`curl https://api-marketplace.scaleway.com/images/ | jq '.images[].versions[].id'`).

This image version (the one that your command returns) has multiple variants (to match a particular commercial type, architecture, and zone).
These variants are named "local images" (as they are images for local volumes) and it is these local images IDs that you need to create a server (`curl https://api-marketplace.scaleway.com/images/ | jq '.images[].versions[].local_images[].id'`).

## Instance API

The `https://api.scaleway.com/instance/v1/zones/{zone}/images` endpoint provides directly these local image IDs. That's the difference.

# Solution

We totally agree that it is not very clear and that it should be easier to find a specific (local) image ID. That's why we are working on tools and on a new version of the CLI, totally rewritten. It will support all our products and will provide a better and easier way to find a local image ID.

Meanwhile, you can use [this little command](https://gist.github.com/QuentinBrosse/d8ece883ec0dbcc2dabd2d453945b4fb) to find your image ID.

Sorry for the inconvenience, do not hesitate to re-open this issue if it's not clear! :)
Thanks a lot for your feedback.

**Comment by valvin1** [comment]
@QuentinBrosse thank you for explanations
